### PR TITLE
Added UST Middleware

### PR DESCRIPTION
**Pull request by 0xm3rlin**

### CODE REVIEW

**Comment by DarrenAlex** [comment]
Looks good. 
Would it be better to be able to enable/disable harvests? Just in case something bad happens. 
Would be achieved by adding a simple `isActive` modifier

**Comment by 0xm3rlin** [comment]
> Looks good.
> Would it be better to be able to enable/disable harvests? Just in case something bad happens.
> Would be achieved by adding a simple `isActive` modifier

As this sits on top of the existing strategy, the executorRole can be taken at any time

**Comment by DarrenAlex** [comment]
Source code has been verified [here](https://etherscan.io/address/0xdd43ff09a0ac59d3a1560316c65fd7b9f81f9209#code).

**Review by 0xCalibur — APPROVED** [review]
I made some esthetic changes, really basic fork testing, and a deploy script. Looks good to me

**Comment by DarrenAlex** [comment]
[Deployed](https://etherscan.io/tx/0xdf6a3ff7b63b72db89bc6e484d09eee5ac9a35d52702a211ad718c2371ca9870).
Source code has been verified [here](https://etherscan.io/address/0x2a86e1b39b9fa919ee72fc220f39a4cd6aefac90#code).

**Pull request merged**
